-- CHIQUISTRUKIS - Oracle schema idempotente (English identifiers, SB-04)
-- Source of truth for attendance: attendance_day (month is calculated)

SET ECHO OFF
SET VERIFY OFF
SET FEEDBACK ON
SET SERVEROUTPUT ON

WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT ============================================
PROMPT [2/5] CREANDO / VALIDANDO TABLAS
PROMPT ============================================

DECLARE
    FUNCTION table_exists(p_table_name IN VARCHAR2) RETURN BOOLEAN IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM user_tables
        WHERE table_name = UPPER(p_table_name);

        RETURN v_count > 0;
    END;

    FUNCTION constraint_exists(p_constraint_name IN VARCHAR2) RETURN BOOLEAN IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM user_constraints
        WHERE constraint_name = UPPER(p_constraint_name);

        RETURN v_count > 0;
    END;

    FUNCTION primary_key_exists(p_table_name IN VARCHAR2) RETURN BOOLEAN IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM user_constraints
        WHERE table_name = UPPER(p_table_name)
          AND constraint_type = 'P';

        RETURN v_count > 0;
    END;

    FUNCTION column_exists(
        p_table_name IN VARCHAR2,
        p_column_name IN VARCHAR2
    ) RETURN BOOLEAN IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM user_tab_columns
        WHERE table_name = UPPER(p_table_name)
          AND column_name = UPPER(p_column_name);

        RETURN v_count > 0;
    END;

    PROCEDURE create_table_if_missing(
        p_table_name IN VARCHAR2,
        p_sql IN VARCHAR2
    ) IS
    BEGIN
        IF table_exists(p_table_name) THEN
            DBMS_OUTPUT.PUT_LINE('[OK] Tabla ' || UPPER(p_table_name) || ' ya existe');
        ELSE
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('[CREATE] Tabla ' || UPPER(p_table_name) || ' creada');
        END IF;
    END;

    PROCEDURE add_constraint_if_missing(
        p_constraint_name IN VARCHAR2,
        p_sql IN VARCHAR2
    ) IS
    BEGIN
        IF constraint_exists(p_constraint_name) THEN
            DBMS_OUTPUT.PUT_LINE('[OK] Constraint ' || UPPER(p_constraint_name) || ' ya existe');
        ELSE
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('[CREATE] Constraint ' || UPPER(p_constraint_name) || ' creada');
        END IF;
    END;

    PROCEDURE drop_constraint_if_exists(
        p_constraint_name IN VARCHAR2,
        p_sql IN VARCHAR2
    ) IS
    BEGIN
        IF constraint_exists(p_constraint_name) THEN
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('[DROP] Constraint ' || UPPER(p_constraint_name) || ' removida');
        END IF;
    END;

    PROCEDURE add_primary_key_if_missing(
        p_table_name IN VARCHAR2,
        p_constraint_name IN VARCHAR2,
        p_sql IN VARCHAR2
    ) IS
    BEGIN
        IF constraint_exists(p_constraint_name) THEN
            DBMS_OUTPUT.PUT_LINE('[OK] Primary key ' || UPPER(p_constraint_name) || ' ya existe');
        ELSIF primary_key_exists(p_table_name) THEN
            DBMS_OUTPUT.PUT_LINE('[OK] Tabla ' || UPPER(p_table_name) || ' ya tiene primary key');
        ELSE
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('[CREATE] Primary key ' || UPPER(p_constraint_name) || ' creada');
        END IF;
    END;

    PROCEDURE add_column_if_missing(
        p_table_name IN VARCHAR2,
        p_column_name IN VARCHAR2,
        p_sql IN VARCHAR2
    ) IS
    BEGIN
        IF column_exists(p_table_name, p_column_name) THEN
            DBMS_OUTPUT.PUT_LINE('[OK] Columna ' || UPPER(p_table_name) || '.' || UPPER(p_column_name) || ' ya existe');
        ELSE
            EXECUTE IMMEDIATE p_sql;
            DBMS_OUTPUT.PUT_LINE('[CREATE] Columna ' || UPPER(p_table_name) || '.' || UPPER(p_column_name) || ' creada');
        END IF;
    END;
BEGIN
    create_table_if_missing('user_account', q'[
        CREATE TABLE user_account (
            id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
            username        VARCHAR2(50)  NOT NULL,
            password_hash   VARCHAR2(255) NOT NULL,
            role_name       VARCHAR2(30)  NOT NULL,
            is_active       CHAR(1)       DEFAULT 'Y' NOT NULL
        )
    ]');

    create_table_if_missing('institution', q'[
        CREATE TABLE institution (
            id               NUMBER GENERATED BY DEFAULT AS IDENTITY,
            ugel             VARCHAR2(100) NOT NULL,
            school_name      VARCHAR2(150) NOT NULL,
            modular_code     VARCHAR2(20)  NOT NULL,
            education_level  VARCHAR2(50),
            shift_name       VARCHAR2(30),
            is_active        CHAR(1) DEFAULT 'Y' NOT NULL
        )
    ]');

    create_table_if_missing('staff_member', q'[
        CREATE TABLE staff_member (
            id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
            dni               VARCHAR2(8)   NOT NULL,
            last_names        VARCHAR2(100) NOT NULL,
            first_names       VARCHAR2(100) NOT NULL,
            job_title         VARCHAR2(80)  NOT NULL,
            employment_status VARCHAR2(50),
            is_active         CHAR(1) DEFAULT 'Y' NOT NULL,
            registered_at     DATE DEFAULT TRUNC(SYSDATE) NOT NULL
        )
    ]');

    create_table_if_missing('staff_institution', q'[
        CREATE TABLE staff_institution (
            id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
            staff_member_id NUMBER NOT NULL,
            institution_id  NUMBER NOT NULL,
            start_date      DATE   NOT NULL,
            end_date        DATE,
            is_active       CHAR(1) DEFAULT 'Y' NOT NULL
        )
    ]');

    create_table_if_missing('biometric_import', q'[
        CREATE TABLE biometric_import (
            id               NUMBER GENERATED BY DEFAULT AS IDENTITY,
            file_name        VARCHAR2(255) NOT NULL,
            file_path        VARCHAR2(500),
            uploaded_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            user_account_id  NUMBER,
            status           VARCHAR2(20) DEFAULT 'draft' NOT NULL,
            period_start     DATE,
            period_end       DATE,
            total_rows       NUMBER DEFAULT 0,
            ok_rows          NUMBER DEFAULT 0,
            error_rows       NUMBER DEFAULT 0,
            matched_rows     NUMBER DEFAULT 0,
            new_rows         NUMBER DEFAULT 0
        )
    ]');

    create_table_if_missing('biometric_mark', q'[
        CREATE TABLE biometric_mark (
            id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
            staff_member_id     NUMBER NOT NULL,
            biometric_import_id NUMBER,
            marked_at           TIMESTAMP NOT NULL,
            mark_type           VARCHAR2(20) NOT NULL,
            status              VARCHAR2(20) DEFAULT 'valid' NOT NULL
        )
    ]');

    create_table_if_missing('inconsistency', q'[
        CREATE TABLE inconsistency (
            id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
            mark_id        NUMBER NOT NULL,
            issue_type     VARCHAR2(40) NOT NULL,
            description    VARCHAR2(300),
            status         VARCHAR2(20) DEFAULT 'pending' NOT NULL,
            detected_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]');

    create_table_if_missing('justification', q'[
        CREATE TABLE justification (
            id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
            staff_member_id   NUMBER NOT NULL,
            start_date        DATE NOT NULL,
            end_date          DATE NOT NULL,
            norm_code         VARCHAR2(10) NOT NULL,
            with_pay          CHAR(1) NOT NULL,
            reason            VARCHAR2(300),
            support_file_path VARCHAR2(500),
            registered_by_id  NUMBER,
            registered_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            status            VARCHAR2(20) DEFAULT 'active' NOT NULL
        )
    ]');

    create_table_if_missing('attendance_day', q'[
        CREATE TABLE attendance_day (
            id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
            staff_member_id   NUMBER NOT NULL,
            biometric_import_id NUMBER,
            attendance_date   DATE NOT NULL,
            status            VARCHAR2(30) NOT NULL,
            late_minutes      NUMBER DEFAULT 0 NOT NULL,
            justification_id  NUMBER
        )
    ]');

    add_column_if_missing('attendance_day', 'biometric_import_id',
        'ALTER TABLE attendance_day ADD biometric_import_id NUMBER');

    create_table_if_missing('audit_log', q'[
        CREATE TABLE audit_log (
            id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
            user_account_id NUMBER NOT NULL,
            entity_name     VARCHAR2(40) NOT NULL,
            entity_id       NUMBER NOT NULL,
            action_name     VARCHAR2(20) NOT NULL,
            old_value       CLOB,
            new_value       CLOB,
            created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]');

    create_table_if_missing('ai_usage_log', q'[
        CREATE TABLE ai_usage_log (
            id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
            biometric_import_id NUMBER NOT NULL,
            file_name           VARCHAR2(255) NOT NULL,
            provider            VARCHAR2(50) NOT NULL,
            model_name          VARCHAR2(80) NOT NULL,
            input_tokens        NUMBER DEFAULT 0 NOT NULL,
            output_tokens       NUMBER DEFAULT 0 NOT NULL,
            total_tokens        NUMBER DEFAULT 0 NOT NULL,
            estimated_cost_usd  NUMBER(12, 6) DEFAULT 0 NOT NULL,
            created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]');

    add_primary_key_if_missing('user_account', 'pk_user_account', 'ALTER TABLE user_account ADD CONSTRAINT pk_user_account PRIMARY KEY (id)');
    add_constraint_if_missing('uk_user_account_username', 'ALTER TABLE user_account ADD CONSTRAINT uk_user_account_username UNIQUE (username)');
    add_constraint_if_missing('ck_user_account_active', q'[ALTER TABLE user_account ADD CONSTRAINT ck_user_account_active CHECK (is_active IN ('Y', 'N'))]');

    add_primary_key_if_missing('institution', 'pk_institution', 'ALTER TABLE institution ADD CONSTRAINT pk_institution PRIMARY KEY (id)');
    add_constraint_if_missing('uk_institution_modular_code', 'ALTER TABLE institution ADD CONSTRAINT uk_institution_modular_code UNIQUE (modular_code)');
    add_constraint_if_missing('ck_institution_active', q'[ALTER TABLE institution ADD CONSTRAINT ck_institution_active CHECK (is_active IN ('Y', 'N'))]');

    add_primary_key_if_missing('staff_member', 'pk_staff_member', 'ALTER TABLE staff_member ADD CONSTRAINT pk_staff_member PRIMARY KEY (id)');
    add_constraint_if_missing('uk_staff_member_dni', 'ALTER TABLE staff_member ADD CONSTRAINT uk_staff_member_dni UNIQUE (dni)');
    add_constraint_if_missing('ck_staff_member_active', q'[ALTER TABLE staff_member ADD CONSTRAINT ck_staff_member_active CHECK (is_active IN ('Y', 'N'))]');
    add_constraint_if_missing('ck_staff_member_dni_len', q'[ALTER TABLE staff_member ADD CONSTRAINT ck_staff_member_dni_len CHECK (REGEXP_LIKE(dni, '^[0-9]{8}$'))]');

    add_primary_key_if_missing('staff_institution', 'pk_staff_institution', 'ALTER TABLE staff_institution ADD CONSTRAINT pk_staff_institution PRIMARY KEY (id)');
    add_constraint_if_missing('fk_si_staff', 'ALTER TABLE staff_institution ADD CONSTRAINT fk_si_staff FOREIGN KEY (staff_member_id) REFERENCES staff_member (id)');
    add_constraint_if_missing('fk_si_inst', 'ALTER TABLE staff_institution ADD CONSTRAINT fk_si_inst FOREIGN KEY (institution_id) REFERENCES institution (id)');
    add_constraint_if_missing('ck_si_active', q'[ALTER TABLE staff_institution ADD CONSTRAINT ck_si_active CHECK (is_active IN ('Y', 'N'))]');

    add_primary_key_if_missing('biometric_import', 'pk_biometric_import', 'ALTER TABLE biometric_import ADD CONSTRAINT pk_biometric_import PRIMARY KEY (id)');
    add_constraint_if_missing('fk_bi_user', 'ALTER TABLE biometric_import ADD CONSTRAINT fk_bi_user FOREIGN KEY (user_account_id) REFERENCES user_account (id)');
    add_constraint_if_missing('ck_bi_status', q'[ALTER TABLE biometric_import ADD CONSTRAINT ck_bi_status CHECK (status IN ('draft', 'confirmed', 'cancelled'))]');

    add_primary_key_if_missing('biometric_mark', 'pk_biometric_mark', 'ALTER TABLE biometric_mark ADD CONSTRAINT pk_biometric_mark PRIMARY KEY (id)');
    add_constraint_if_missing('fk_bm_staff', 'ALTER TABLE biometric_mark ADD CONSTRAINT fk_bm_staff FOREIGN KEY (staff_member_id) REFERENCES staff_member (id)');
    add_constraint_if_missing('fk_bm_import', 'ALTER TABLE biometric_mark ADD CONSTRAINT fk_bm_import FOREIGN KEY (biometric_import_id) REFERENCES biometric_import (id)');
    add_constraint_if_missing('ck_bm_type', q'[ALTER TABLE biometric_mark ADD CONSTRAINT ck_bm_type CHECK (mark_type IN ('entry', 'exit'))]');
    add_constraint_if_missing('ck_bm_status', q'[ALTER TABLE biometric_mark ADD CONSTRAINT ck_bm_status CHECK (status IN ('valid', 'inconsistent', 'corrected'))]');

    add_primary_key_if_missing('inconsistency', 'pk_inconsistency', 'ALTER TABLE inconsistency ADD CONSTRAINT pk_inconsistency PRIMARY KEY (id)');
    add_constraint_if_missing('fk_inc_mark', 'ALTER TABLE inconsistency ADD CONSTRAINT fk_inc_mark FOREIGN KEY (mark_id) REFERENCES biometric_mark (id)');
    add_constraint_if_missing('ck_inc_status', q'[ALTER TABLE inconsistency ADD CONSTRAINT ck_inc_status CHECK (status IN ('pending', 'reviewed', 'corrected'))]');

    add_primary_key_if_missing('justification', 'pk_justification', 'ALTER TABLE justification ADD CONSTRAINT pk_justification PRIMARY KEY (id)');
    add_constraint_if_missing('fk_just_staff', 'ALTER TABLE justification ADD CONSTRAINT fk_just_staff FOREIGN KEY (staff_member_id) REFERENCES staff_member (id)');
    add_constraint_if_missing('fk_just_user', 'ALTER TABLE justification ADD CONSTRAINT fk_just_user FOREIGN KEY (registered_by_id) REFERENCES user_account (id)');
    add_constraint_if_missing('ck_just_pay', q'[ALTER TABLE justification ADD CONSTRAINT ck_just_pay CHECK (with_pay IN ('Y', 'N'))]');
    add_constraint_if_missing('ck_just_status', q'[ALTER TABLE justification ADD CONSTRAINT ck_just_status CHECK (status IN ('active', 'cancelled'))]');
    add_constraint_if_missing('ck_just_dates', 'ALTER TABLE justification ADD CONSTRAINT ck_just_dates CHECK (end_date >= start_date)');

    add_primary_key_if_missing('attendance_day', 'pk_attendance_day', 'ALTER TABLE attendance_day ADD CONSTRAINT pk_attendance_day PRIMARY KEY (id)');
    add_constraint_if_missing('fk_ad_staff', 'ALTER TABLE attendance_day ADD CONSTRAINT fk_ad_staff FOREIGN KEY (staff_member_id) REFERENCES staff_member (id)');
    add_constraint_if_missing('fk_ad_import', 'ALTER TABLE attendance_day ADD CONSTRAINT fk_ad_import FOREIGN KEY (biometric_import_id) REFERENCES biometric_import (id)');
    add_constraint_if_missing('fk_ad_just', 'ALTER TABLE attendance_day ADD CONSTRAINT fk_ad_just FOREIGN KEY (justification_id) REFERENCES justification (id)');
    drop_constraint_if_exists('uk_ad_staff_date', 'ALTER TABLE attendance_day DROP CONSTRAINT uk_ad_staff_date');
    add_constraint_if_missing('uk_ad_staff_date_import', 'ALTER TABLE attendance_day ADD CONSTRAINT uk_ad_staff_date_import UNIQUE (staff_member_id, attendance_date, biometric_import_id)');
    add_constraint_if_missing('ck_ad_late', 'ALTER TABLE attendance_day ADD CONSTRAINT ck_ad_late CHECK (late_minutes >= 0)');
    add_constraint_if_missing('ck_ad_status', q'[ALTER TABLE attendance_day ADD CONSTRAINT ck_ad_status CHECK (status IN ('present', 'late', 'absent', 'justified', 'leave', 'permission'))]');

    add_primary_key_if_missing('audit_log', 'pk_audit_log', 'ALTER TABLE audit_log ADD CONSTRAINT pk_audit_log PRIMARY KEY (id)');
    add_constraint_if_missing('fk_audit_user', 'ALTER TABLE audit_log ADD CONSTRAINT fk_audit_user FOREIGN KEY (user_account_id) REFERENCES user_account (id)');

    add_primary_key_if_missing('ai_usage_log', 'pk_ai_usage_log', 'ALTER TABLE ai_usage_log ADD CONSTRAINT pk_ai_usage_log PRIMARY KEY (id)');
    add_constraint_if_missing('fk_ai_usage_import', 'ALTER TABLE ai_usage_log ADD CONSTRAINT fk_ai_usage_import FOREIGN KEY (biometric_import_id) REFERENCES biometric_import (id)');
    add_constraint_if_missing('ck_ai_usage_cost', 'ALTER TABLE ai_usage_log ADD CONSTRAINT ck_ai_usage_cost CHECK (estimated_cost_usd >= 0)');
END;
/

PROMPT ============================================
PROMPT [OK] TABLAS Y CONSTRAINTS VALIDADAS
PROMPT ============================================

EXIT SUCCESS
